// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentOperator():Promise<main.OperatorInfo>;

export function IsAuthenticated():Promise<boolean>;

export function IsFirstRun():Promise<boolean>;

export function IsLocked():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function SetupInitialOperator(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateActivity():Promise<void>;
