// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFamilyMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFamilyMember'](arg1, arg2, arg3);
}

export function CreateCitizen(arg1) {
  return window['go']['main']['App']['CreateCitizen'](arg1);
}

export function CreateRegistration(arg1) {
  return window['go']['main']['App']['CreateRegistration'](arg1);
}

export function DeleteCitizen(arg1) {
  return window['go']['main']['App']['DeleteCitizen'](arg1);
}

export function DeregisterCitizen(arg1, arg2) {
  return window['go']['main']['App']['DeregisterCitizen'](arg1, arg2);
}

export function ExportCitizens(arg1, arg2) {
  return window['go']['main']['App']['ExportCitizens'](arg1, arg2);
}

export function ExportCitizensToExcel() {
  return window['go']['main']['App']['ExportCitizensToExcel']();
}

export function ExportCustomCitizensToExcel(arg1, arg2) {
  return window['go']['main']['App']['ExportCustomCitizensToExcel'](arg1, arg2);
}

export function GenerateCitizenCertificate(arg1, arg2) {
  return window['go']['main']['App']['GenerateCitizenCertificate'](arg1, arg2);
}

export function GenerateFamilyStatusCertificate(arg1) {
  return window['go']['main']['App']['GenerateFamilyStatusCertificate'](arg1);
}

export function GetAuditLogs(arg1) {
  return window['go']['main']['App']['GetAuditLogs'](arg1);
}

export function GetCitizen(arg1) {
  return window['go']['main']['App']['GetCitizen'](arg1);
}

export function GetCurrentOperator() {
  return window['go']['main']['App']['GetCurrentOperator']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetFamilyMembers(arg1) {
  return window['go']['main']['App']['GetFamilyMembers'](arg1);
}

export function GetRegistrationHistory(arg1) {
  return window['go']['main']['App']['GetRegistrationHistory'](arg1);
}

export function ImportCitizens() {
  return window['go']['main']['App']['ImportCitizens']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function ListCitizens(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCitizens'](arg1, arg2, arg3);
}

export function ListRegistrations(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListRegistrations'](arg1, arg2, arg3, arg4);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RemoveFamilyMember(arg1, arg2) {
  return window['go']['main']['App']['RemoveFamilyMember'](arg1, arg2);
}

export function RestoreCitizen(arg1) {
  return window['go']['main']['App']['RestoreCitizen'](arg1);
}

export function SearchCitizens(arg1, arg2) {
  return window['go']['main']['App']['SearchCitizens'](arg1, arg2);
}

export function SetupInitialOperator(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupInitialOperator'](arg1, arg2, arg3);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateActivity() {
  return window['go']['main']['App']['UpdateActivity']();
}

export function UpdateCitizen(arg1, arg2) {
  return window['go']['main']['App']['UpdateCitizen'](arg1, arg2);
}
