// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCitizen(arg1) {
  return window['go']['main']['App']['CreateCitizen'](arg1);
}

export function CreateRegistration(arg1) {
  return window['go']['main']['App']['CreateRegistration'](arg1);
}

export function DeleteCitizen(arg1) {
  return window['go']['main']['App']['DeleteCitizen'](arg1);
}

export function DeregisterCitizen(arg1, arg2) {
  return window['go']['main']['App']['DeregisterCitizen'](arg1, arg2);
}

export function GetCitizen(arg1) {
  return window['go']['main']['App']['GetCitizen'](arg1);
}

export function GetCurrentOperator() {
  return window['go']['main']['App']['GetCurrentOperator']();
}

export function GetRegistrationHistory(arg1) {
  return window['go']['main']['App']['GetRegistrationHistory'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function ListCitizens(arg1, arg2) {
  return window['go']['main']['App']['ListCitizens'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RestoreCitizen(arg1) {
  return window['go']['main']['App']['RestoreCitizen'](arg1);
}

export function SearchCitizens(arg1, arg2) {
  return window['go']['main']['App']['SearchCitizens'](arg1, arg2);
}

export function SetupInitialOperator(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupInitialOperator'](arg1, arg2, arg3);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateActivity() {
  return window['go']['main']['App']['UpdateActivity']();
}

export function UpdateCitizen(arg1, arg2) {
  return window['go']['main']['App']['UpdateCitizen'](arg1, arg2);
}
