// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentOperator() {
  return window['go']['main']['App']['GetCurrentOperator']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SetupInitialOperator(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupInitialOperator'](arg1, arg2, arg3);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateActivity() {
  return window['go']['main']['App']['UpdateActivity']();
}
