// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddFamilyMember(arg1:number,arg2:number,arg3:string):Promise<void>;

export function CreateCitizen(arg1:models.CitizenInput):Promise<models.CitizenOutput>;

export function CreateRegistration(arg1:models.RegistrationInput):Promise<models.RegistrationOutput>;

export function DeleteCitizen(arg1:number):Promise<void>;

export function DeregisterCitizen(arg1:number,arg2:string):Promise<void>;

export function ExportCitizens(arg1:string,arg2:string):Promise<string>;

export function ExportCitizensToExcel():Promise<string>;

export function ExportCustomCitizensToExcel(arg1:Array<number>,arg2:Array<string>):Promise<string>;

export function GenerateCitizenCertificate(arg1:number,arg2:models.FamilyCertificateOptions):Promise<string>;

export function GenerateFamilyStatusCertificate(arg1:models.FamilyCertificateOptions):Promise<string>;

export function GetAuditLogs(arg1:number):Promise<Array<models.AuditLogOutput>>;

export function GetCitizen(arg1:number):Promise<models.CitizenOutput>;

export function GetCurrentOperator():Promise<models.Operator>;

export function GetDashboardStats():Promise<models.StatsOutput>;

export function GetFamilyMembers(arg1:number):Promise<Array<models.FamilyMemberOutput>>;

export function GetRegistrationHistory(arg1:number):Promise<Array<models.RegistrationOutput>>;

export function ImportCitizens():Promise<number>;

export function IsAuthenticated():Promise<boolean>;

export function IsFirstRun():Promise<boolean>;

export function IsLocked():Promise<boolean>;

export function ListCitizens(arg1:number,arg2:number,arg3:boolean):Promise<models.CitizenListResult>;

export function ListRegistrations(arg1:string,arg2:any,arg3:number,arg4:number):Promise<models.RegistrationListResult>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function RecoverByMasterKey(arg1:string,arg2:string):Promise<void>;

export function RemoveFamilyMember(arg1:number,arg2:number):Promise<void>;

export function RestoreCitizen(arg1:number):Promise<void>;

export function SearchCitizens(arg1:string,arg2:string):Promise<Array<models.CitizenOutput>>;

export function SetupInitialOperator(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateActivity():Promise<void>;

export function UpdateCitizen(arg1:number,arg2:models.CitizenInput):Promise<models.CitizenOutput>;
