// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {database} from '../models';
import {main} from '../models';

export function CreateCitizen(arg1:services.CitizenInput):Promise<services.CitizenOutput>;

export function CreateRegistration(arg1:database.RegistrationInput):Promise<database.RegistrationOutput>;

export function DeleteCitizen(arg1:number):Promise<void>;

export function DeregisterCitizen(arg1:number,arg2:string):Promise<void>;

export function ExportCitizens(arg1:string,arg2:string):Promise<string>;

export function GenerateCertificate(arg1:number):Promise<string>;

export function GetAuditLogs(arg1:number):Promise<Array<database.AuditLogOutput>>;

export function GetCitizen(arg1:number):Promise<services.CitizenOutput>;

export function GetCurrentOperator():Promise<main.OperatorInfo>;

export function GetDashboardStats():Promise<services.StatsOutput>;

export function GetRegistrationHistory(arg1:number):Promise<Array<database.RegistrationOutput>>;

export function IsAuthenticated():Promise<boolean>;

export function IsFirstRun():Promise<boolean>;

export function IsLocked():Promise<boolean>;

export function ListCitizens(arg1:number,arg2:number):Promise<services.CitizenListResult>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function RestoreCitizen(arg1:number):Promise<void>;

export function SearchCitizens(arg1:string,arg2:string):Promise<Array<services.CitizenOutput>>;

export function SetupInitialOperator(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateActivity():Promise<void>;

export function UpdateCitizen(arg1:number,arg2:services.CitizenInput):Promise<void>;
